import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/src/components/Layout";

export const metadata: Metadata = {
  title: "maryam store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Layout>
        {children}
        </Layout>
        </body>
    </html>
  );
}
